version: '3'

services:
  softvisiontest:
    build: .
    container_name: softapp
    network_mode: host
    port:
      - "8000:000"
    command: bash -c "uvicorn main:app"
    volumes:
      - ./soft.db:/softvisiontest/soft.db:delegated
